server:
  http_endpoint: :8999
  max_req_body_size: 209715200 # 1024 * 1024 * 200 = 200M

log:
  std: true
  level: debug
  logs:
    - enable: true
      filename: log/workflow-info.log
      level: info
      max_size: 10
      max_backups: 10
      max_age: 30
    - enable: true
      filename: log/workflow-err.log
      level: error
      max_size: 10
      max_backups: 10
      max_age: 30

jwt:
  signing-key: "zhYZAr7Q7JstuEXQBx5p2MdUtfsC7CY5"

db:
  name: mysql # mysql | postgres | tidb | oceanbase
  mysql:
    address: localhost:3306
    user: root
    password: Wanwu123456
    database: opencoze
    max_open_conns: 16
    max_idle_conns: 16
    log_mode: true
  postgres:
    address: localhost:5432
    user: postgres
    password: Wanwu123456
    database: opencoze
    max_open_conns: 16
    max_idle_conns: 16
    log_mode: true
  tidb:
    address: localhost:4000
    user: root
    password: Wanwu123456
    database: opencoze
    max_open_conns: 16
    max_idle_conns: 16
    log_mode: true
  oceanbase:
    address: localhost:2881
    user: root
    password: Wanwu123456
    database: opencoze
    max_open_conns: 16
    max_idle_conns: 16
    log_mode: true

redis:
  host: localhost
  port: 6379
  username:
  password: Wanwu123456
  standalone: true
  master_name: mymaster

minio:
  endpoint: localhost:9000
  user: root
  password: Wanwu123456

icons:
  - id: 1
    url: /api/static/icon/icon-Start-v2.jpg
  - id: 2
    url: /api/static/icon/icon-End-v2.jpg
  - id: 3
    url: /api/static/icon/icon-LLM-v2.png
  - id: 5
    url: /api/static/icon/icon-Code-v2.jpg
  - id: 8
    url: /api/static/icon/icon-Condition-v2.jpg
  - id: 9
    url: /api/static/icon/icon-Workflow-v2.jpg
  - id: 13
    url: /api/static/icon/icon-Output-v2.jpg
  - id: 15
    url: /api/static/icon/icon-StrConcat-v2.jpg
  - id: 19
    url: api/static/icon/icon-Break-v2.jpg
  - id: 20
    url: api/static/icon/icon-LoopSetVariable-v2.jpg
  - id: 21
    url: /api/static/icon/icon-Loop-v2.jpg
  - id: 22
    url: /api/static/icon/icon-Intent-v2.jpg
  - id: 28
    url: /api/static/icon/icon-Batch-v2.jpg
  - id: 29
    url: api/static/icon/icon-Continue-v2.jpg
  - id: 30
    url: /api/static/icon/icon-Input-v2.jpg
  - id: 32
    url: /api/static/icon/icon-VariableMerge.jpg
  - id: 45
    url: /api/static/icon/icon-HTTP.png
  - id: 58
    url: /api/static/icon/icon-to_json.png
  - id: 1006
    url: /api/static/icon/icon-KnowledgeQuery-v2.jpg
  - id: 1007
    url: /api/static/icon/icon-KnowledgeQuery-v2.jpg
  - id: 1008
    url: /api/static/icon/icon-KnowledgeQuery-v2.jpg
  - id: 1009
    url: /api/static/icon/icon-MCP-v2.png
  - id: 1010
    url: /api/static/icon/icon-GUI-v2.jpg
  - id: 1059
    url: /api/static/icon/icon-from_json.png
  
workflow:
  # ！！！同步于：backend/conf/workflow/config.yaml
  # ！！！同步于：backend/conf/workflow/config.yaml
  # ！！！同步于：backend/conf/workflow/config.yaml
  NodeOfCodeConfig:
    SupportThirdPartModules:
      - httpx
      - numpy